Extract statistics data file path from opendkim.conf

diff --git a/stats/opendkim-reportstats.in b/stats/opendkim-reportstats.in
--- a/stats/opendkim-reportstats.in
+++ b/stats/opendkim-reportstats.in
@@ -9,24 +9,33 @@
 #
 
 ##
-## Directory and filename of the stats file generated by opendkim(8)
+##  opendkim(8) configuration file location
 ##
 
-OPENDKIMSTATSDIR="/var/db/opendkim"
-OPENDKIMSTATSFILE="stats.dat"
+OPENDKIMCONFIG="/etc/mail/opendkim.conf"
 
 ##
-## Owner of that file
-## (Leave empty to skip the re-creation step and let opendkim(8) do it)
+##  Owner and group of the statistics file
+##  (Leave empty to skip the re-creation step and let opendkim(8) do it)
 ##
 
 OPENDKIMDATOWNER="mailnull:mailnull"
 
-##
+##  ===========================================
 ##  NO USER SERVICEABLE PARTS BEYOND THIS POINT
-##
+##  ===========================================
 
 PROGNAME=`basename $0`
+
+OPENDKIMSTATS=`awk '$1 == "Statistics" { print $2 }'`
+if [ x"$OPENDKIMSTATS" = x"" ]
+then
+	echo "${PROGNAME}: can't determine statistics file location from ${OPENDKIMCONFIG}"
+	exit 1
+fi
+
+OPENDKIMSTATSDIR=`dirname $OPENDKIMSTATS`
+OPENDKIMSTATSFILE=`basename $OPENDKIMSTATS`
 
 REPORTERNAME="OpenDKIM Filter User"
 REPORTEREMAIL="<`whoami`@$HOSTNAME>"
